import { Project } from "@/types/project";

export const projectsData: Project[] = [
  {
    title: "OmniWallet",
    period: "-",
    shortDescription:
      "OmniWallet adalah platform dompet digital (e-wallet) fullstack berbasis microservices yang mensimulasikan ekosistem pembayaran seperti ShopeePay, dibangun dengan Go dan Next.js 15.",
    details: [
      "Microservices Architecture: Sistem terdiri dari API Gateway, User Service, Wallet Service, dan Notification Worker yang berjalan secara independen via Docker Compose.",
      "Double-Entry Ledger: Setiap transaksi dijamin ACID sehingga tidak ada dana yang hilang atau tergandakan.",
      "Idempotent API: Retry request tidak menyebabkan transaksi ganda, memastikan keamanan dan konsistensi data keuangan.",
      "P2P Transfer: Transfer saldo antar pengguna secara real-time dengan validasi PIN transaksi.",
      "Top-up via Xendit Virtual Account: Integrasi payment gateway Xendit (Fixed VA) lengkap dengan webhook callback dan simulate endpoint untuk mode test.",
      "Async Notification: Notifikasi event transaksi menggunakan RabbitMQ — pesan tetap tersimpan di queue meski worker sempat down.",
      "Admin Dashboard: Manajemen pengguna dan monitoring transaksi melalui antarmuka Next.js 15 yang responsif.",
      "KYC & Profil: Sistem verifikasi identitas pengguna (KYC) dan manajemen profil dengan PIN keamanan transaksi.",
    ],
    image: "/images/projects/omni-wallet.png",
    imageHint: "digital wallet fintech",
    tags: [
      "Go",
      "Gin",
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Zustand",
      "MySQL",
      "Redis",
      "RabbitMQ",
      "Docker",
      "Xendit",
      "Microservices",
      "JWT",
    ],
    github: "https://github.com/srgjo27/omni-wallet",
  },
  {
    title: "DesaPOS",
    period: "-",
    shortDescription:
      "DesaPOS adalah sistem kasir dan pencatatan inventaris yang ringan, responsif, dan mudah digunakan oleh pengurus BUMDes, dengan dukungan mode offline-first berbasis PWA.",
    details: [
      "Interactive POS Register: Halaman kasir super cepat dengan keranjang belanja yang dikelola via State Management (Pinia) agar tidak hilang saat pindah menu.",
      "Offline-First (PWA): Menggunakan Service Workers agar transaksi tetap bisa dicatat saat internet atau listrik padam, lalu otomatis sync ke server saat koneksi kembali.",
      "Role-Based Access: Pemisahan akses antara Kasir (melayani transaksi) dan Kepala BUMDes (melihat dashboard laba/rugi).",
      "One-Click Report: Generate laporan transaksi harian/bulanan dalam format PDF yang rapi dengan satu klik.",
      "Login & Shift Management: Kasir login menggunakan PIN/Password dan mencatat uang modal di laci kasir saat memulai shift harian.",
      "Smart Checkout: Sistem otomatis menghitung total harga, diskon, dan kembalian, serta memotong stok inventaris secara real-time.",
      "Struk & Nota: Mendukung pencetakan struk thermal via Bluetooth/USB atau pengiriman nota transaksi melalui WhatsApp.",
      "Dashboard Analitik: Kepala BUMDes dapat memantau barang terlaris dan total omzet bulanan melalui dashboard analitik.",
    ],
    image: "/images/projects/desa-pos.png",
    imageHint: "point of sale kasir",
    tags: ["Vue 3", "Pinia", "Vite", "TailwindCSS", "Headless UI", "Axios", "Supabase", "PostgreSQL", "PWA"],
    github: "https://github.com/srgjo27/desa-pos",
  },
  {
    title: "Agora",
    period: "-",
    shortDescription:
      "",
    details: [

    ],
    image: "/images/projects/agora.png",
    imageHint: "website",
    tags: ["React", "Next.js", "UI/UX", "REST API", "Tailwind CSS", "Go"],
    github: "",
  },
  {
    title: "Agora",
    period: "-",
    shortDescription:
      "Agora adalah platform komunitas modern untuk diskusi bermakna, dibangun dengan Next.js 16 dan Go (Gin) menggunakan Clean Architecture.",
    details: [
      "Modern Design: Tema terang (Slate/White/Blue) dengan animasi halus menggunakan Framer Motion.",
      "Responsive Layout: Adaptive design untuk berbagai ukuran layar dengan Tailwind CSS 4.",
      "Dynamic Forum: Sistem thread dan diskusi dengan fitur posting, komentar, dan voting (upvote/downvote).",
      "Secure Authentication: Sistem login dan registrasi dengan JWT (backend) dan Redux Persist (frontend).",
      "User Dashboard: Manajemen postingan, profil, dan aktivitas pengguna secara personal.",
      "Content Categorization: Sistem kategorisasi konten untuk organisasi thread yang lebih baik.",
      "Real-time Interactions: UI reaktif berbasis React 19 dengan state management Redux Toolkit.",
      "Scalable Backend: Clean Architecture dengan Go (Gin), PostgreSQL, Redis caching, dan Docker.",
    ],
    image: "/images/projects/agora.png",
    imageHint: "community forum platform",
    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Go", "Gin", "PostgreSQL", "Redis", "Docker", "Redux"],
    github: "https://github.com/srgjo27/fe-agora",
  },
  {
    title: "Product Recommendation with Algorithms",
    period: "Sep 2023 - Jul 2024",
    shortDescription:
      "A machine learning-powered system providing accurate recommendations, featuring a Laravel front-end and a Python back-end.",
    details: [
      "Developed a front-end using HTML, CSS, JavaScript, and PHP with the Laravel framework, incorporating AJAX for asynchronous data updates.",
      "Utilized MySQL for efficient database management.",
      "Implemented back-end machine learning algorithms in Python, improving product recommendation accuracy by 80%.",
      "Integrated a REST API to connect the front-end and back-end, accelerating data exchange.",
      "Optimized the recommendation model using MAE and RMSE, achieving an error rate below 1.",
      "Deployed the application on a VPS to ensure optimal scalability and performance for high user traffic.",
    ],
    image: "https://placehold.co/600x400.png",
    imageHint: "recommendation algorithm",
    tags: [
      "Laravel",
      "PHP",
      "Machine Learning",
      "Python",
      "MySQL",
      "AJAX",
      "REST API",
    ],
    github: "https://github.com/srgjo27/ud_anthony",
  },
  {
    title: "DELHUB",
    period: "Jan 2023 - Jun 2024",
    shortDescription:
      "A mobile app to digitize academic administration for students and supervisors, featuring scheduling, grading, and document uploads.",
    details: [
      "Designing and developing DELHUB mobile applications for the digitization of Final Project (TA), Final Project (PA), and Practical Work (KP) administration for students and supervisors.",
      "Build key features, including tutoring schedule management, grade input, and document upload.",
      "Integrate the mobile application (Flutter) with the admin dashboard (Laravel) through REST API, which speeds up the data synchronization process.",
      "Implemented real-time notifications using Firebase Messaging for schedule and status updates, improving system responsiveness.",
    ],
    image: "https://placehold.co/600x400.png",
    imageHint: "mobile app",
    tags: ["Flutter", "Laravel", "REST API", "Firebase", "Mobile Development"],
  },
  {
    title: "MARKETKU",
    period: "Oct 2022 - Des 2022",
    shortDescription:
      "A JavaFX desktop application for market management, featuring inventory and sales tracking with a MySQL backend.",
    details: [
      "Built advanced desktop applications using Java FX with an OOP approach, ensuring code modularity and scalability.",
      "Designed an interactive and intuitive user interface using FXML, significantly improving user experience.",
      "Integrated MySQL database via JDBC, enabling efficient data handling and ensuring reliable, real-time connectivity.",
      "Implemented key features such as inventory management, sales monitoring, and user productivity.",
    ],
    image: "https://placehold.co/600x400.png",
    imageHint: "desktop application",
    tags: ["JavaFX", "Java", "MySQL", "JDBC", "Desktop App"],
    github: "https://github.com/srgjo27/MarketKu-Desktop-Web",
  },
];